server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/callgoshop_dev
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE