server:
  port: 8080
  ssl:
    enabled: true
    key-store: src/main/resources/keystore.p12
    key-store-password: wldhkdl1!
    key-store-type: PKCS12
    key-alias: callgomall
spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/gysoft02
    username: gysoft02
    password: NEED_TO_INPUT_ON_SECRET
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
image:
  upload:
    dir: /gysoft02/tomcat/webapps/img

#server:
#  port: 8080
#  ssl:
#    enabled: false
#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/gysoft02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
#    username: gysoft02
#    password: wldhkdl1!
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        show_sql: false
#        format_sql: true
#        use_sql_comments: true
#        default_batch_fetch_size: 100
#  servlet:
#    multipart:
#      max-file-size: 512MB
#      max-request-size: 512MB
#      enabled: true
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    #org.hibernate.type: TRACE
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.orm.jdbc.extract: TRACE